spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.c2lfcbm3wbfx.ap-northeast-2.rds.amazonaws.com:13306/pre?serverTimezone=UTC&characterEncoding=UTF-8
    username:
    password:

config:
  domain: http://pre-project43.s3-website.ap-northeast-2.amazonaws.com/

mail:
  address:
    admin:
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 300
  refresh-token-expiration-minutes: 4200